import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateDummyDataWithUser1735943000000 implements MigrationInterface {
  name = 'CreateDummyDataWithUser1735943000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Insert 100 users (1 User per Employee)
    await queryRunner.query(`
      INSERT INTO users (email, password, role) 
      VALUES
        ('user1@example.com', 'password1', 'employee'),
        ('user2@example.com', 'password2', 'employee'),
        ('user3@example.com', 'password3', 'employee'),
        ('user4@example.com', 'password4', 'employee'),
        ('user5@example.com', 'password5', 'employee'),
        ('user6@example.com', 'password6', 'employee'),
        ('user7@example.com', 'password7', 'employee'),
        ('user8@example.com', 'password8', 'employee'),
        ('user9@example.com', 'password9', 'employee'),
        ('user10@example.com', 'password10', 'employee'),
        ('user11@example.com', 'password11', 'employee'),
        ('user12@example.com', 'password12', 'employee'),
        ('user13@example.com', 'password13', 'employee'),
        ('user14@example.com', 'password14', 'employee'),
        ('user15@example.com', 'password15', 'employee'),
        ('user16@example.com', 'password16', 'employee'),
        ('user17@example.com', 'password17', 'employee'),
        ('user18@example.com', 'password18', 'employee'),
        ('user19@example.com', 'password19', 'employee'),
        ('user20@example.com', 'password20', 'employee'),
        ('user21@example.com', 'password21', 'employee'),
        ('user22@example.com', 'password22', 'employee'),
        ('user23@example.com', 'password23', 'employee'),
        ('user24@example.com', 'password24', 'employee'),
        ('user25@example.com', 'password25', 'employee'),
        ('user26@example.com', 'password26', 'employee'),
        ('user27@example.com', 'password27', 'employee'),
        ('user28@example.com', 'password28', 'employee'),
        ('user29@example.com', 'password29', 'employee'),
        ('user30@example.com', 'password30', 'employee'),
        ('user31@example.com', 'password31', 'employee'),
        ('user32@example.com', 'password32', 'employee'),
        ('user33@example.com', 'password33', 'employee'),
        ('user34@example.com', 'password34', 'employee'),
        ('user35@example.com', 'password35', 'employee'),
        ('user36@example.com', 'password36', 'employee'),
        ('user37@example.com', 'password37', 'employee'),
        ('user38@example.com', 'password38', 'employee'),
        ('user39@example.com', 'password39', 'employee'),
        ('user40@example.com', 'password40', 'employee'),
        ('user41@example.com', 'password41', 'employee'),
        ('user42@example.com', 'password42', 'employee'),
        ('user43@example.com', 'password43', 'employee'),
        ('user44@example.com', 'password44', 'employee'),
        ('user45@example.com', 'password45', 'employee'),
        ('user46@example.com', 'password46', 'employee'),
        ('user47@example.com', 'password47', 'employee'),
        ('user48@example.com', 'password48', 'employee'),
        ('user49@example.com', 'password49', 'employee'),
        ('user50@example.com', 'password50', 'employee'),
        ('user51@example.com', 'password51', 'employee'),
        ('user52@example.com', 'password52', 'employee'),
        ('user53@example.com', 'password53', 'employee'),
        ('user54@example.com', 'password54', 'employee'),
        ('user55@example.com', 'password55', 'employee'),
        ('user56@example.com', 'password56', 'employee'),
        ('user57@example.com', 'password57', 'employee'),
        ('user58@example.com', 'password58', 'employee'),
        ('user59@example.com', 'password59', 'employee'),
        ('user60@example.com', 'password60', 'employee'),
        ('user61@example.com', 'password61', 'employee'),
        ('user62@example.com', 'password62', 'employee'),
        ('user63@example.com', 'password63', 'employee'),
        ('user64@example.com', 'password64', 'employee'),
        ('user65@example.com', 'password65', 'employee'),
        ('user66@example.com', 'password66', 'employee'),
        ('user67@example.com', 'password67', 'employee'),
        ('user68@example.com', 'password68', 'employee'),
        ('user69@example.com', 'password69', 'employee'),
        ('user70@example.com', 'password70', 'employee'),
        ('user71@example.com', 'password71', 'employee'),
        ('user72@example.com', 'password72', 'employee'),
        ('user73@example.com', 'password73', 'employee'),
        ('user74@example.com', 'password74', 'employee'),
        ('user75@example.com', 'password75', 'employee'),
        ('user76@example.com', 'password76', 'employee'),
        ('user77@example.com', 'password77', 'employee'),
        ('user78@example.com', 'password78', 'employee'),
        ('user79@example.com', 'password79', 'employee'),
        ('user80@example.com', 'password80', 'employee'),
        ('user81@example.com', 'password81', 'employee'),
        ('user82@example.com', 'password82', 'employee'),
        ('user83@example.com', 'password83', 'employee'),
        ('user84@example.com', 'password84', 'employee'),
        ('user85@example.com', 'password85', 'employee'),
        ('user86@example.com', 'password86', 'employee'),
        ('user87@example.com', 'password87', 'employee'),
        ('user88@example.com', 'password88', 'employee'),
        ('user89@example.com', 'password89', 'employee'),
        ('user90@example.com', 'password90', 'employee'),
        ('user91@example.com', 'password91', 'employee'),
        ('user92@example.com', 'password92', 'employee'),
        ('user93@example.com', 'password93', 'employee'),
        ('user94@example.com', 'password94', 'employee'),
        ('user95@example.com', 'password95', 'employee'),
        ('user96@example.com', 'password96', 'employee'),
        ('user97@example.com', 'password97', 'employee'),
        ('user98@example.com', 'password98', 'employee'),
        ('user99@example.com', 'password99', 'employee'),
        ('user100@example.com', 'password100', 'employee'),
        ('admin@example.com', 'password100', 'admin'),
        ('company1@example.com', 'password100', 'company'),
        ('company2@example.com', 'password100', 'company'),
        ('company3@example.com', 'password100', 'company'),
        ('company4@example.com', 'password100', 'company'),
        ('company5@example.com', 'password100', 'company'),
        ('company6@example.com', 'password100', 'company'),
        ('company7@example.com', 'password100', 'company'),
        ('company8@example.com', 'password100', 'company'),
        ('company9@example.com', 'password100', 'company'),
        ('company10@example.com', 'password100', 'company');
    `);

    await queryRunner.query(`
        INSERT INTO company (name, address, userId) 
        VALUES
          ('KIT SYSTEM SOLUTIONS VIETNAM', '123 Street, City', (SELECT id FROM users WHERE email = 'company1@example.com')),
          ('IT Company', '456 Avenue, Town', (SELECT id FROM users WHERE email = 'company2@example.com')),
          ('PizzaHut', '789 Road, Village', (SELECT id FROM users WHERE email = 'company3@example.com')),
          ('FSoft', '1011 Blvd, Metro', (SELECT id FROM users WHERE email = 'company4@example.com')),
          ('Company E', '1213 Drive, Suburb', (SELECT id FROM users WHERE email = 'company5@example.com')),
          ('Company F', '1415 Crescent, Downtown', (SELECT id FROM users WHERE email = 'company6@example.com')),
          ('Company G', '1617 Parkway, Uptown', (SELECT id FROM users WHERE email = 'company7@example.com')),
          ('Company H', '1819 Lane, Old Town', (SELECT id FROM users WHERE email = 'company8@example.com')),
          ('Company I', '2021 Road, New City', (SELECT id FROM users WHERE email = 'company9@example.com')),
          ('Company J', '2223 Avenue, Coastal', (SELECT id FROM users WHERE email = 'company10@example.com'));
      `);     
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DELETE FROM users');
    await queryRunner.query('DELETE FROM company');
  }
}
