version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install -g serverless@3.38.0
      - npm install
  build:
    commands:
      - echo Building application...
      - npm run build
  post_build:
    commands:
      - echo Deploying to Lambda...
      - npm run sls:deploy-$STAGE

artifacts:
  files:
    - dist/**
