version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building application...
      - npm run build
  post_build:
    commands:
      - echo Serverless version...
      - npx serverless --version
      - echo Deploying to Lambda...
      - npm run sls:deploy-dev

cache:
  paths:
    - node_modules
